-- FACILITY OPS v0.4.0 upgrade
-- 사용자 관리 / 변경 이력 / 휴지통 / 본인 또는 관리자만 삭제
-- Supabase SQL Editor에서 전체를 한 번에 실행하세요.

begin;

-- 1) 사용자 최근 접속 정보
alter table public.profiles add column if not exists last_seen timestamptz;

-- 2) 삭제 대신 휴지통으로 보내기 위한 컬럼
alter table public.facilities add column if not exists deleted_at timestamptz;
alter table public.facilities add column if not exists deleted_by uuid references auth.users(id) on delete set null;
alter table public.inspections add column if not exists deleted_at timestamptz;
alter table public.inspections add column if not exists deleted_by uuid references auth.users(id) on delete set null;
alter table public.issues add column if not exists deleted_at timestamptz;
alter table public.issues add column if not exists deleted_by uuid references auth.users(id) on delete set null;
alter table public.schedules add column if not exists deleted_at timestamptz;
alter table public.schedules add column if not exists deleted_by uuid references auth.users(id) on delete set null;

-- 3) 변경 이력 테이블
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  action text not null check (action in ('create','update','delete','restore','profile_update')),
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default '',
  created_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb
);

create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_record_idx on public.audit_logs(table_name, record_id);

alter table public.audit_logs enable row level security;

-- 4) 권한 판정 함수. SECURITY DEFINER로 profiles RLS 재귀를 피합니다.
create or replace function public.facility_ops_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

create or replace function public.facility_ops_can_edit()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('admin','member')
  );
$$;

grant execute on function public.facility_ops_is_admin() to authenticated;
grant execute on function public.facility_ops_can_edit() to authenticated;

-- 5) 로그인 시 최근 접속 시각 갱신
create or replace function public.facility_ops_touch_my_profile()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  update public.profiles
  set last_seen = now(), updated_at = now()
  where id = auth.uid();
end;
$$;

grant execute on function public.facility_ops_touch_my_profile() to authenticated;

-- 6) 관리자 사용자 목록: auth.users의 이메일은 직원에게 노출하지 않고 아이디 부분만 반환
create or replace function public.facility_ops_admin_list_users()
returns table (
  id uuid,
  login_id text,
  display_name text,
  role text,
  last_seen timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.facility_ops_is_admin() then
    raise exception '관리자만 사용자 목록을 볼 수 있습니다.' using errcode = '42501';
  end if;

  return query
  select
    u.id,
    split_part(coalesce(u.email,''), '@', 1) as login_id,
    coalesce(p.display_name, split_part(coalesce(u.email,''), '@', 1)) as display_name,
    coalesce(p.role, 'member') as role,
    p.last_seen,
    u.created_at
  from auth.users u
  left join public.profiles p on p.id = u.id
  order by coalesce(p.display_name, split_part(coalesce(u.email,''), '@', 1));
end;
$$;

grant execute on function public.facility_ops_admin_list_users() to authenticated;

-- 7) 관리자 사용자 이름/권한 변경
create or replace function public.facility_ops_admin_update_profile(
  p_user_id uuid,
  p_display_name text,
  p_role text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_name text;
begin
  if not public.facility_ops_is_admin() then
    raise exception '관리자만 사용자 권한을 변경할 수 있습니다.' using errcode = '42501';
  end if;

  if p_role not in ('admin','member','viewer') then
    raise exception '올바르지 않은 권한입니다.';
  end if;

  -- 실수로 자기 관리자 권한을 없애서 시스템에서 잠기는 것을 방지
  if p_user_id = auth.uid() and p_role <> 'admin' then
    raise exception '현재 로그인한 관리자 자신의 관리자 권한은 해제할 수 없습니다.';
  end if;

  update public.profiles
  set display_name = nullif(trim(p_display_name), ''),
      role = p_role,
      updated_at = now()
  where id = p_user_id;

  select coalesce(display_name, '관리자') into v_actor_name
  from public.profiles where id = auth.uid();

  insert into public.audit_logs(table_name, record_id, action, actor_id, actor_name, details)
  values(
    'profiles', p_user_id::text, 'profile_update', auth.uid(), coalesce(v_actor_name,'관리자'),
    jsonb_build_object('display_name', p_display_name, 'role', p_role)
  );
end;
$$;

grant execute on function public.facility_ops_admin_update_profile(uuid,text,text) to authenticated;

-- 8) 변경 이력 자동 기록
create or replace function public.facility_ops_audit_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_action text;
  v_record_id text;
  v_actor uuid := auth.uid();
  v_actor_name text := '';
  v_old jsonb;
  v_new jsonb;
begin
  if tg_op = 'INSERT' then
    v_action := 'create';
    v_record_id := new.id::text;
    v_new := to_jsonb(new);
  elsif tg_op = 'UPDATE' then
    v_record_id := new.id::text;
    v_old := to_jsonb(old);
    v_new := to_jsonb(new);

    if old.deleted_at is null and new.deleted_at is not null then
      v_action := 'delete';
    elsif old.deleted_at is not null and new.deleted_at is null then
      v_action := 'restore';
    else
      v_action := 'update';
    end if;
  else
    return coalesce(new, old);
  end if;

  if v_actor is not null then
    select coalesce(p.display_name, split_part(coalesce(u.email,''),'@',1), '')
      into v_actor_name
    from auth.users u
    left join public.profiles p on p.id = u.id
    where u.id = v_actor;
  end if;

  insert into public.audit_logs(table_name, record_id, action, actor_id, actor_name, details)
  values(
    tg_table_name,
    v_record_id,
    v_action,
    v_actor,
    coalesce(v_actor_name,''),
    case when tg_op = 'INSERT'
      then jsonb_build_object('new', v_new)
      else jsonb_build_object('old', v_old, 'new', v_new)
    end
  );

  return new;
end;
$$;

drop trigger if exists facilities_audit_v04 on public.facilities;
create trigger facilities_audit_v04 after insert or update on public.facilities
for each row execute function public.facility_ops_audit_row();

drop trigger if exists inspections_audit_v04 on public.inspections;
create trigger inspections_audit_v04 after insert or update on public.inspections
for each row execute function public.facility_ops_audit_row();

drop trigger if exists issues_audit_v04 on public.issues;
create trigger issues_audit_v04 after insert or update on public.issues
for each row execute function public.facility_ops_audit_row();

drop trigger if exists schedules_audit_v04 on public.schedules;
create trigger schedules_audit_v04 after insert or update on public.schedules
for each row execute function public.facility_ops_audit_row();

-- 9) 삭제는 본인 또는 관리자만 가능. 실제 행 삭제 대신 휴지통 처리.
create or replace function public.facility_ops_soft_delete(p_table text, p_id text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner uuid;
  v_deleted_at timestamptz;
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if p_table not in ('facilities','inspections','issues','schedules') then
    raise exception '허용되지 않은 데이터 종류입니다.';
  end if;

  execute format('select created_by, deleted_at from public.%I where id = $1', p_table)
    into v_owner, v_deleted_at using p_id;

  if not found then
    raise exception '항목을 찾을 수 없습니다.';
  end if;

  if v_deleted_at is not null then
    return;
  end if;

  if not public.facility_ops_is_admin() and v_owner is distinct from v_uid then
    raise exception '본인이 등록한 항목만 삭제할 수 있습니다.' using errcode = '42501';
  end if;

  execute format('update public.%I set deleted_at = now(), deleted_by = $1 where id = $2', p_table)
    using v_uid, p_id;
end;
$$;

grant execute on function public.facility_ops_soft_delete(text,text) to authenticated;

-- 10) 휴지통 목록 / 복원은 관리자만
create or replace function public.facility_ops_admin_list_trash()
returns table (
  table_name text,
  record_id text,
  title text,
  deleted_at timestamptz,
  deleted_by uuid,
  created_by uuid
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.facility_ops_is_admin() then
    raise exception '관리자만 휴지통을 볼 수 있습니다.' using errcode = '42501';
  end if;

  return query
    select 'facilities'::text, f.id::text, f.name::text, f.deleted_at, f.deleted_by, f.created_by
    from public.facilities f where f.deleted_at is not null
  union all
    select 'inspections'::text, i.id::text,
           ('점검 · ' || coalesce(i.date::text,''))::text, i.deleted_at, i.deleted_by, i.created_by
    from public.inspections i where i.deleted_at is not null
  union all
    select 'issues'::text, q.id::text, q.title::text, q.deleted_at, q.deleted_by, q.created_by
    from public.issues q where q.deleted_at is not null
  union all
    select 'schedules'::text, s.id::text, s.title::text, s.deleted_at, s.deleted_by, s.created_by
    from public.schedules s where s.deleted_at is not null
  order by deleted_at desc;
end;
$$;

grant execute on function public.facility_ops_admin_list_trash() to authenticated;

create or replace function public.facility_ops_admin_restore_record(p_table text, p_id text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.facility_ops_is_admin() then
    raise exception '관리자만 휴지통 항목을 복원할 수 있습니다.' using errcode = '42501';
  end if;

  if p_table not in ('facilities','inspections','issues','schedules') then
    raise exception '허용되지 않은 데이터 종류입니다.';
  end if;

  execute format('update public.%I set deleted_at = null, deleted_by = null where id = $1', p_table)
    using p_id;
end;
$$;

grant execute on function public.facility_ops_admin_restore_record(text,text) to authenticated;

-- 11) profiles: 본인 조회 + 관리자 전체 조회
alter table public.profiles enable row level security;
drop policy if exists "profiles_read_self" on public.profiles;
drop policy if exists "profiles_read_admin" on public.profiles;
create policy "profiles_read_self" on public.profiles
for select to authenticated using (id = auth.uid());
create policy "profiles_read_admin" on public.profiles
for select to authenticated using (public.facility_ops_is_admin());

-- 12) audit_logs는 관리자만 조회. 직접 작성/수정/삭제는 금지.
drop policy if exists "audit_logs_admin_read" on public.audit_logs;
create policy "audit_logs_admin_read" on public.audit_logs
for select to authenticated using (public.facility_ops_is_admin());

revoke all on public.audit_logs from anon;
revoke insert, update, delete on public.audit_logs from authenticated;
grant select on public.audit_logs to authenticated;

-- 13) 일반 화면에는 휴지통 데이터가 보이지 않도록 읽기 정책 교체
--     등록/수정은 member/admin, 직접 DELETE는 불가.
do $$
declare
  t text;
begin
  foreach t in array array['facilities','inspections','issues','schedules'] loop
    execute format('drop policy if exists %I on public.%I', t || '_read', t);
    execute format('drop policy if exists %I on public.%I', t || '_write', t);
    execute format('drop policy if exists %I on public.%I', t || '_insert_v04', t);
    execute format('drop policy if exists %I on public.%I', t || '_update_v04', t);
    execute format('drop policy if exists %I on public.%I', t || '_delete_v04', t);

    execute format(
      'create policy %I on public.%I for select to authenticated using (deleted_at is null)',
      t || '_read', t
    );
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (public.facility_ops_can_edit() and deleted_at is null)',
      t || '_insert_v04', t
    );
    execute format(
      'create policy %I on public.%I for update to authenticated using (public.facility_ops_can_edit() and deleted_at is null) with check (public.facility_ops_can_edit() and deleted_at is null)',
      t || '_update_v04', t
    );
  end loop;
end $$;

-- hard delete는 권한 자체도 제거. 삭제는 facility_ops_soft_delete RPC만 사용.
revoke delete on public.facilities, public.inspections, public.issues, public.schedules from authenticated;

-- 필요한 기본 권한 유지
grant select, insert, update on public.facilities, public.inspections, public.issues, public.schedules to authenticated;
grant select on public.profiles to authenticated;

commit;
