-- FACILITY OPS v0.4.3 — SECURITY FINAL
-- 선행: supabase_v0.4_upgrade.sql -> supabase_v0.4.1_security_core.sql -> supabase_v0.4.2_security_hardening.sql
-- 목적: 계정 상태 / RPC 실행권한 잠금 / 메타데이터 컬럼 권한 / 데이터 길이 제한 / 보안 이벤트 로그
begin;

alter table public.profiles add column if not exists account_status text;

update public.profiles
set account_status = case when coalesce(approved, false) then 'active' else 'pending' end
where account_status is null;

alter table public.profiles alter column account_status set default 'pending';
alter table public.profiles alter column account_status set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_account_status_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_account_status_check
      check (account_status in ('pending','active','suspended','disabled')) not valid;
  end if;
end $$;

update public.profiles p
set account_status = 'active', approved = true, role = 'admin', updated_at = now()
where p.id in (
  select u.id from auth.users u where lower(u.email) = 'admin@facility.local'
);

create or replace function public.facility_ops_is_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.approved = true
      and p.account_status = 'active'
  );
$$;

create or replace function public.facility_ops_is_approved()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.facility_ops_is_active();
$$;

create or replace function public.facility_ops_has_admin_role()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.approved = true
      and p.account_status = 'active'
      and p.role = 'admin'
  );
$$;

create or replace function public.facility_ops_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.facility_ops_has_admin_role()
     and coalesce(auth.jwt()->>'aal','aal1') = 'aal2';
$$;

create or replace function public.facility_ops_can_edit()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.approved = true
      and p.account_status = 'active'
      and (
        p.role = 'member'
        or (p.role = 'admin' and coalesce(auth.jwt()->>'aal','aal1') = 'aal2')
      )
  );
$$;

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default '',
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists security_events_created_at_idx
  on public.security_events(created_at desc);

create index if not exists security_events_actor_idx
  on public.security_events(actor_id, created_at desc);

alter table public.security_events enable row level security;

drop policy if exists "security_events_admin_read" on public.security_events;
create policy "security_events_admin_read"
on public.security_events
for select
to authenticated
using (public.facility_ops_is_admin());

revoke all on public.security_events from anon;
revoke insert, update, delete on public.security_events from authenticated;
grant select on public.security_events to authenticated;

create or replace function public.facility_ops_admin_list_users_v043()
returns table (
  id uuid,
  login_id text,
  display_name text,
  role text,
  approved boolean,
  account_status text,
  last_seen timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.facility_ops_is_admin() then
    raise exception '관리자 2단계 인증이 필요합니다.' using errcode = '42501';
  end if;

  return query
  select
    u.id,
    split_part(coalesce(u.email,''), '@', 1) as login_id,
    coalesce(p.display_name, split_part(coalesce(u.email,''), '@', 1)) as display_name,
    coalesce(p.role, 'member') as role,
    coalesce(p.approved, false) as approved,
    coalesce(p.account_status, case when coalesce(p.approved,false) then 'active' else 'pending' end) as account_status,
    p.last_seen,
    u.created_at
  from auth.users u
  left join public.profiles p on p.id = u.id
  order by coalesce(p.display_name, split_part(coalesce(u.email,''), '@', 1));
end;
$$;

create or replace function public.facility_ops_admin_update_profile_v043(
  p_user_id uuid,
  p_display_name text,
  p_role text,
  p_account_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_name text;
  v_old_status text;
begin
  if not public.facility_ops_is_admin() then
    raise exception '관리자 2단계 인증이 필요합니다.' using errcode = '42501';
  end if;

  if p_role not in ('admin','member','viewer') then
    raise exception '올바르지 않은 권한입니다.';
  end if;

  if p_account_status not in ('pending','active','suspended','disabled') then
    raise exception '올바르지 않은 계정 상태입니다.';
  end if;

  if char_length(coalesce(trim(p_display_name),'')) > 80 then
    raise exception '표시 이름은 80자 이하여야 합니다.';
  end if;

  if p_user_id = auth.uid()
     and (p_role <> 'admin' or p_account_status <> 'active') then
    raise exception '현재 관리자 자신의 관리자 권한 또는 활성 상태는 해제할 수 없습니다.';
  end if;

  select p.account_status into v_old_status
  from public.profiles p
  where p.id = p_user_id;

  update public.profiles
  set display_name = nullif(trim(p_display_name), ''),
      role = p_role,
      account_status = p_account_status,
      approved = (p_account_status = 'active'),
      updated_at = now()
  where id = p_user_id;

  if not found then
    raise exception '사용자 프로필을 찾을 수 없습니다.';
  end if;

  select coalesce(display_name, '관리자') into v_actor_name
  from public.profiles where id = auth.uid();

  insert into public.audit_logs(table_name, record_id, action, actor_id, actor_name, details)
  values(
    'profiles',
    p_user_id::text,
    'profile_update',
    auth.uid(),
    coalesce(v_actor_name,'관리자'),
    jsonb_build_object(
      'display_name', p_display_name,
      'role', p_role,
      'account_status', p_account_status
    )
  );

  if coalesce(v_old_status,'pending') is distinct from p_account_status then
    insert into public.security_events(actor_id, actor_name, event_type, details)
    values(
      auth.uid(),
      coalesce(v_actor_name,'관리자'),
      'account_status_change',
      jsonb_build_object(
        'target_user_id', p_user_id,
        'before', coalesce(v_old_status,'pending'),
        'after', p_account_status
      )
    );
  end if;
end;
$$;

create or replace function public.facility_ops_log_security_event(
  p_event_type text,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text := '';
  v_event text := trim(coalesce(p_event_type,''));
  v_details jsonb := coalesce(p_details,'{}'::jsonb);
begin
  if auth.uid() is null or not public.facility_ops_is_active() then
    raise exception '활성 로그인 계정이 필요합니다.' using errcode = '42501';
  end if;

  if v_event not in (
    'login_success',
    'logout',
    'idle_logout',
    'admin_center_open',
    'backup_export',
    'backup_import',
    'security_test',
    'security_events_view',
    'mfa_verified'
  ) then
    raise exception '허용되지 않은 보안 이벤트입니다.';
  end if;

  if octet_length(v_details::text) > 4096 then
    raise exception '보안 이벤트 상세 정보가 너무 큽니다.';
  end if;

  select coalesce(p.display_name, split_part(coalesce(u.email,''),'@',1), '')
    into v_name
  from auth.users u
  left join public.profiles p on p.id = u.id
  where u.id = auth.uid();

  insert into public.security_events(actor_id, actor_name, event_type, details)
  values(auth.uid(), coalesce(v_name,''), v_event, v_details);
end;
$$;

do $$
declare
  t text;
begin
  foreach t in array array['facilities','inspections','issues','schedules'] loop
    execute format('drop policy if exists %I on public.%I', t || '_read', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.facility_ops_is_active() and deleted_at is null and (not public.facility_ops_has_admin_role() or public.facility_ops_is_admin()))',
      t || '_read', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_insert_v041', t);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (public.facility_ops_can_edit() and created_by = auth.uid() and deleted_at is null)',
      t || '_insert_v041', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_update_v041', t);
    execute format(
      'create policy %I on public.%I for update to authenticated using (public.facility_ops_can_edit() and deleted_at is null and (public.facility_ops_is_admin() or created_by = auth.uid())) with check (public.facility_ops_can_edit() and deleted_at is null and (public.facility_ops_is_admin() or created_by = auth.uid()))',
      t || '_update_v041', t
    );
  end loop;
end $$;

drop policy if exists "profiles_read_admin" on public.profiles;
create policy "profiles_read_admin"
on public.profiles
for select
to authenticated
using (public.facility_ops_is_admin());

drop policy if exists "audit_logs_admin_read" on public.audit_logs;
create policy "audit_logs_admin_read"
on public.audit_logs
for select
to authenticated
using (public.facility_ops_is_admin());

revoke insert, update on public.facilities, public.inspections, public.issues, public.schedules from authenticated;

grant insert (name,location,category,status,install_date,last_inspection,next_inspection,vendor,note)
  on public.facilities to authenticated;
grant update (name,location,category,status,install_date,last_inspection,next_inspection,vendor,note)
  on public.facilities to authenticated;

grant insert (facility_id,date,result,inspector,note,next_date)
  on public.inspections to authenticated;
grant update (facility_id,date,result,inspector,note,next_date)
  on public.inspections to authenticated;

grant insert (facility_id,date,completed_date,title,severity,status,cost,note)
  on public.issues to authenticated;
grant update (facility_id,date,completed_date,title,severity,status,cost,note)
  on public.issues to authenticated;

grant insert (date,type,title,facility_id,status,note)
  on public.schedules to authenticated;
grant update (date,type,title,facility_id,status,note)
  on public.schedules to authenticated;

do $$
begin
  if not exists (select 1 from pg_constraint where conname='facilities_name_len_v043' and conrelid='public.facilities'::regclass) then
    alter table public.facilities add constraint facilities_name_len_v043 check (char_length(btrim(name)) between 1 and 100) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='facilities_location_len_v043' and conrelid='public.facilities'::regclass) then
    alter table public.facilities add constraint facilities_location_len_v043 check (char_length(location) <= 100) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='facilities_category_len_v043' and conrelid='public.facilities'::regclass) then
    alter table public.facilities add constraint facilities_category_len_v043 check (char_length(category) <= 50) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='facilities_vendor_len_v043' and conrelid='public.facilities'::regclass) then
    alter table public.facilities add constraint facilities_vendor_len_v043 check (char_length(vendor) <= 100) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='facilities_note_len_v043' and conrelid='public.facilities'::regclass) then
    alter table public.facilities add constraint facilities_note_len_v043 check (char_length(note) <= 2000) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname='inspections_inspector_len_v043' and conrelid='public.inspections'::regclass) then
    alter table public.inspections add constraint inspections_inspector_len_v043 check (char_length(inspector) <= 80) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='inspections_note_len_v043' and conrelid='public.inspections'::regclass) then
    alter table public.inspections add constraint inspections_note_len_v043 check (char_length(note) <= 2000) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname='issues_title_len_v043' and conrelid='public.issues'::regclass) then
    alter table public.issues add constraint issues_title_len_v043 check (char_length(btrim(title)) between 1 and 200) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='issues_note_len_v043' and conrelid='public.issues'::regclass) then
    alter table public.issues add constraint issues_note_len_v043 check (char_length(note) <= 2000) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='issues_cost_range_v043' and conrelid='public.issues'::regclass) then
    alter table public.issues add constraint issues_cost_range_v043 check (cost between 0 and 1000000000) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname='schedules_type_len_v043' and conrelid='public.schedules'::regclass) then
    alter table public.schedules add constraint schedules_type_len_v043 check (char_length(type) <= 50) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='schedules_title_len_v043' and conrelid='public.schedules'::regclass) then
    alter table public.schedules add constraint schedules_title_len_v043 check (char_length(btrim(title)) between 1 and 200) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='schedules_note_len_v043' and conrelid='public.schedules'::regclass) then
    alter table public.schedules add constraint schedules_note_len_v043 check (char_length(note) <= 2000) not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname='profiles_display_name_len_v043' and conrelid='public.profiles'::regclass) then
    alter table public.profiles add constraint profiles_display_name_len_v043 check (display_name is null or char_length(display_name) <= 80) not valid;
  end if;
end $$;

do $$
declare
  sig text;
begin
  foreach sig in array array[
    'public.facility_ops_is_active()',
    'public.facility_ops_is_approved()',
    'public.facility_ops_has_admin_role()',
    'public.facility_ops_is_admin()',
    'public.facility_ops_can_edit()',
    'public.facility_ops_touch_my_profile()',
    'public.facility_ops_admin_list_users()',
    'public.facility_ops_admin_update_profile(uuid,text,text)',
    'public.facility_ops_soft_delete(text,text)',
    'public.facility_ops_admin_list_trash()',
    'public.facility_ops_admin_restore_record(text,text)',
    'public.facility_ops_admin_list_users_v041()',
    'public.facility_ops_admin_update_profile_v041(uuid,text,text,boolean)',
    'public.facility_ops_admin_import_backup(jsonb)',
    'public.facility_ops_security_status()',
    'public.facility_ops_admin_list_users_v043()',
    'public.facility_ops_admin_update_profile_v043(uuid,text,text,text)',
    'public.facility_ops_log_security_event(text,jsonb)'
  ] loop
    if to_regprocedure(sig) is not null then
      execute 'revoke all on function ' || sig || ' from public';
      execute 'revoke all on function ' || sig || ' from anon';
    end if;
  end loop;
end $$;

grant execute on function public.facility_ops_is_active() to authenticated;
grant execute on function public.facility_ops_is_approved() to authenticated;
grant execute on function public.facility_ops_has_admin_role() to authenticated;
grant execute on function public.facility_ops_is_admin() to authenticated;
grant execute on function public.facility_ops_can_edit() to authenticated;
grant execute on function public.facility_ops_touch_my_profile() to authenticated;
grant execute on function public.facility_ops_soft_delete(text,text) to authenticated;
grant execute on function public.facility_ops_admin_list_trash() to authenticated;
grant execute on function public.facility_ops_admin_restore_record(text,text) to authenticated;
grant execute on function public.facility_ops_admin_import_backup(jsonb) to authenticated;
grant execute on function public.facility_ops_security_status() to authenticated;
grant execute on function public.facility_ops_admin_list_users_v043() to authenticated;
grant execute on function public.facility_ops_admin_update_profile_v043(uuid,text,text,text) to authenticated;
grant execute on function public.facility_ops_log_security_event(text,jsonb) to authenticated;

do $$
begin
  if to_regprocedure('public.facility_ops_admin_list_users()') is not null then
    execute 'grant execute on function public.facility_ops_admin_list_users() to authenticated';
  end if;
  if to_regprocedure('public.facility_ops_admin_update_profile(uuid,text,text)') is not null then
    execute 'grant execute on function public.facility_ops_admin_update_profile(uuid,text,text) to authenticated';
  end if;
  if to_regprocedure('public.facility_ops_admin_list_users_v041()') is not null then
    execute 'grant execute on function public.facility_ops_admin_list_users_v041() to authenticated';
  end if;
  if to_regprocedure('public.facility_ops_admin_update_profile_v041(uuid,text,text,boolean)') is not null then
    execute 'grant execute on function public.facility_ops_admin_update_profile_v041(uuid,text,text,boolean) to authenticated';
  end if;
end $$;

revoke all on public.facilities, public.inspections, public.issues, public.schedules,
              public.profiles, public.audit_logs, public.security_events from anon;

revoke delete on public.facilities, public.inspections, public.issues, public.schedules from authenticated;

commit;

-- Supabase Dashboard에서 반드시 별도로 확인할 항목
-- 1) Authentication > Providers > Email: 신규 회원가입 OFF
-- 2) Authentication > Password Security: 최소 12자 + 대/소문자 + 숫자 + 특수문자
-- 3) Authentication > MFA: TOTP ON
-- 4) Bot and Abuse Protection: Turnstile 사용 시 Secret Key 설정
-- GitHub Pages 정적 프론트만으로 위 Dashboard 설정 자체를 변경할 수는 없습니다.
